version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ai-content-backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/chroma_data
      - sqlite_data:/app/data
      - synced_images:/app/static/yandex_sync
      - ./backend/static:/app/static
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: ai-content-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  backend_data:
  sqlite_data:
  synced_images:
